// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chat.sql

package repo

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addUserToChat = `-- name: AddUserToChat :exec
INSERT INTO chat_members (chat_id, user_id)
VALUES ($1, $2)
ON CONFLICT (chat_id, user_id) DO NOTHING
`

type AddUserToChatParams struct {
	ChatID uuid.UUID `json:"chatId"`
	UserID uuid.UUID `json:"userId"`
}

func (q *Queries) AddUserToChat(ctx context.Context, arg AddUserToChatParams) error {
	_, err := q.db.Exec(ctx, addUserToChat, arg.ChatID, arg.UserID)
	return err
}

const chatExists = `-- name: ChatExists :one
SELECT EXISTS (SELECT 1
               FROM chats
               WHERE id = $1)
`

func (q *Queries) ChatExists(ctx context.Context, chatID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, chatExists, chatID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createChat = `-- name: CreateChat :one
INSERT INTO chats (name, type)
VALUES ($1, $2)
RETURNING chats.id
`

type CreateChatParams struct {
	Name pgtype.Text `json:"name"`
	Type string      `json:"type"`
}

func (q *Queries) CreateChat(ctx context.Context, arg CreateChatParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createChat, arg.Name, arg.Type)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getChat = `-- name: GetChat :one
SELECT id, name, type, created_at
FROM chats
WHERE id = $1
`

func (q *Queries) GetChat(ctx context.Context, id uuid.UUID) (Chat, error) {
	row := q.db.QueryRow(ctx, getChat, id)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}

const isUserChatMember = `-- name: IsUserChatMember :one
SELECT EXISTS (SELECT 1
               FROM chat_members
               WHERE chat_id = $1
                 AND user_id = $2) AS is_member
`

type IsUserChatMemberParams struct {
	ChatID uuid.UUID `json:"chatId"`
	UserID uuid.UUID `json:"userId"`
}

func (q *Queries) IsUserChatMember(ctx context.Context, arg IsUserChatMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isUserChatMember, arg.ChatID, arg.UserID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}
