// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: message.sql

package repo

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages(chat_id, sender_id, content)
VALUES ($1, $2, $3)
RETURNING id, chat_id, sender_id, content, created_at
`

type CreateMessageParams struct {
	ChatID   uuid.UUID `json:"chatId"`
	SenderID uuid.UUID `json:"senderId"`
	Content  string    `json:"content"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.ChatID, arg.SenderID, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.SenderID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const getMessagesPaging = `-- name: GetMessagesPaging :many
SELECT m.id, m.chat_id, m.sender_id, m.content, m.created_at, u.id, u.username, u.email, u.password_hash, u.created_at, u.avatar_url, u.email_verified
FROM messages m
         JOIN users u ON u.id = m.sender_id
WHERE m.chat_id = $1::uuid
  AND (
      $2::timestamptz IS NULL
      OR
      (m.created_at, m.id) < ($2::timestamptz, $3::uuid)
      )
ORDER BY m.created_at DESC, m.id DESC
LIMIT $4
`

type GetMessagesPagingParams struct {
	ChatID          uuid.UUID          `json:"chatId"`
	CursorCreatedAt pgtype.Timestamptz `json:"cursorCreatedAt"`
	CursorID        uuid.UUID          `json:"cursorId"`
	Limit           int32              `json:"limit"`
}

type GetMessagesPagingRow struct {
	ID            uuid.UUID          `json:"id"`
	ChatID        uuid.UUID          `json:"chatId"`
	SenderID      uuid.UUID          `json:"senderId"`
	Content       string             `json:"content"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
	ID_2          uuid.UUID          `json:"id2"`
	Username      string             `json:"username"`
	Email         string             `json:"email"`
	PasswordHash  pgtype.Text        `json:"passwordHash"`
	CreatedAt_2   pgtype.Timestamptz `json:"createdAt2"`
	AvatarUrl     pgtype.Text        `json:"avatarUrl"`
	EmailVerified bool               `json:"emailVerified"`
}

func (q *Queries) GetMessagesPaging(ctx context.Context, arg GetMessagesPagingParams) ([]GetMessagesPagingRow, error) {
	rows, err := q.db.Query(ctx, getMessagesPaging,
		arg.ChatID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMessagesPagingRow
	for rows.Next() {
		var i GetMessagesPagingRow
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.SenderID,
			&i.Content,
			&i.CreatedAt,
			&i.ID_2,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.CreatedAt_2,
			&i.AvatarUrl,
			&i.EmailVerified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
