// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Chat struct {
	ID        uuid.UUID          `json:"id"`
	Name      pgtype.Text        `json:"name"`
	Type      string             `json:"type"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}

type ChatMember struct {
	ID       uuid.UUID          `json:"id"`
	ChatID   uuid.UUID          `json:"chatId"`
	UserID   uuid.UUID          `json:"userId"`
	JoinedAt pgtype.Timestamptz `json:"joinedAt"`
}

type Message struct {
	ID        uuid.UUID          `json:"id"`
	ChatID    uuid.UUID          `json:"chatId"`
	SenderID  uuid.UUID          `json:"senderId"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Username     string             `json:"username"`
	Email        string             `json:"email"`
	PasswordHash pgtype.Text        `json:"passwordHash"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
	AvatarUrl    pgtype.Text        `json:"avatarUrl"`
}
