// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package repo

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, password_hash)
VALUES ($1, $2, $3)
RETURNING users.id
`

type CreateUserParams struct {
	Username     string      `json:"username"`
	Email        string      `json:"email"`
	PasswordHash pgtype.Text `json:"passwordHash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.Email, arg.PasswordHash)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getUser = `-- name: GetUser :one
SELECT id, username, email, password_hash, created_at, avatar_url, email_verified
FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.AvatarUrl,
		&i.EmailVerified,
	)
	return i, err
}

const getUserByLogin = `-- name: GetUserByLogin :one
SELECT id, username, email, password_hash, created_at, avatar_url, email_verified
FROM users
WHERE username = $1
   OR email = $1
LIMIT 1
`

func (q *Queries) GetUserByLogin(ctx context.Context, login string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByLogin, login)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.AvatarUrl,
		&i.EmailVerified,
	)
	return i, err
}

const updateUserAvatar = `-- name: UpdateUserAvatar :exec
UPDATE users
SET avatar_url = $1
WHERE id = $2
`

type UpdateUserAvatarParams struct {
	AvatarUrl pgtype.Text `json:"avatarUrl"`
	ID        uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) error {
	_, err := q.db.Exec(ctx, updateUserAvatar, arg.AvatarUrl, arg.ID)
	return err
}

const userWithEmailExists = `-- name: UserWithEmailExists :one
SELECT EXISTS (SELECT 1
               FROM users
               WHERE email = $1)
`

func (q *Queries) UserWithEmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, userWithEmailExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const userWithUsernameExists = `-- name: UserWithUsernameExists :one
SELECT EXISTS (SELECT 1
               FROM users
               WHERE username = $1)
`

func (q *Queries) UserWithUsernameExists(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, userWithUsernameExists, username)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
