// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: message.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages(id, chat_id, sender_id, content, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, chat_id, sender_id, content, created_at
`

type CreateMessageParams struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	ChatID    uuid.UUID          `db:"chat_id" json:"chatId"`
	SenderID  uuid.UUID          `db:"sender_id" json:"senderId"`
	Content   string             `db:"content" json:"content"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ID,
		arg.ChatID,
		arg.SenderID,
		arg.Content,
		arg.CreatedAt,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.SenderID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const getMessagesPaging = `-- name: GetMessagesPaging :many
SELECT m.id, m.chat_id, m.sender_id, m.content, m.created_at, u.id, u.username, u.email, u.email_verified, u.password_hash, u.created_at, u.avatar_url
FROM messages m
         JOIN users u ON u.id = m.sender_id
WHERE m.chat_id = $1::uuid
  AND (
      $2::timestamptz IS NULL
      OR
      (m.created_at, m.id) < ($2::timestamptz, $3::uuid)
      )
ORDER BY m.created_at DESC, m.id DESC
LIMIT $4
`

type GetMessagesPagingParams struct {
	ChatID          uuid.UUID          `db:"chat_id" json:"chatId"`
	CursorCreatedAt pgtype.Timestamptz `db:"cursor_created_at" json:"cursorCreatedAt"`
	CursorID        uuid.UUID          `db:"cursor_id" json:"cursorId"`
	Limit           int32              `db:"limit_" json:"limit"`
}

type GetMessagesPagingRow struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	ChatID        uuid.UUID          `db:"chat_id" json:"chatId"`
	SenderID      uuid.UUID          `db:"sender_id" json:"senderId"`
	Content       string             `db:"content" json:"content"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	ID_2          uuid.UUID          `db:"id_2" json:"id2"`
	Username      string             `db:"username" json:"username"`
	Email         string             `db:"email" json:"email"`
	EmailVerified bool               `db:"email_verified" json:"emailVerified"`
	PasswordHash  pgtype.Text        `db:"password_hash" json:"passwordHash"`
	CreatedAt_2   pgtype.Timestamptz `db:"created_at_2" json:"createdAt2"`
	AvatarUrl     pgtype.Text        `db:"avatar_url" json:"avatarUrl"`
}

func (q *Queries) GetMessagesPaging(ctx context.Context, arg GetMessagesPagingParams) ([]GetMessagesPagingRow, error) {
	rows, err := q.db.Query(ctx, getMessagesPaging,
		arg.ChatID,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetMessagesPagingRow{}
	for rows.Next() {
		var i GetMessagesPagingRow
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.SenderID,
			&i.Content,
			&i.CreatedAt,
			&i.ID_2,
			&i.Username,
			&i.Email,
			&i.EmailVerified,
			&i.PasswordHash,
			&i.CreatedAt_2,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
