// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Chat struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Name      pgtype.Text        `db:"name" json:"name"`
	Type      string             `db:"type" json:"type"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}

type ChatMember struct {
	ID       uuid.UUID          `db:"id" json:"id"`
	ChatID   uuid.UUID          `db:"chat_id" json:"chatId"`
	UserID   uuid.UUID          `db:"user_id" json:"userId"`
	JoinedAt pgtype.Timestamptz `db:"joined_at" json:"joinedAt"`
}

type EmailVerificationCode struct {
	UserID    uuid.UUID          `db:"user_id" json:"userId"`
	CodeHash  string             `db:"code_hash" json:"codeHash"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expiresAt"`
	Attempts  int32              `db:"attempts" json:"attempts"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}

type Message struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	ChatID    uuid.UUID          `db:"chat_id" json:"chatId"`
	SenderID  uuid.UUID          `db:"sender_id" json:"senderId"`
	Content   string             `db:"content" json:"content"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}

type User struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	Username      string             `db:"username" json:"username"`
	Email         string             `db:"email" json:"email"`
	EmailVerified bool               `db:"email_verified" json:"emailVerified"`
	PasswordHash  pgtype.Text        `db:"password_hash" json:"passwordHash"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	AvatarUrl     pgtype.Text        `db:"avatar_url" json:"avatarUrl"`
}
