// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddUserToChat(ctx context.Context, arg AddUserToChatParams) error
	ChatExists(ctx context.Context, chatID uuid.UUID) (bool, error)
	CreateChat(ctx context.Context, arg CreateChatParams) (uuid.UUID, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetChat(ctx context.Context, id uuid.UUID) (Chat, error)
	GetMessagesPaging(ctx context.Context, arg GetMessagesPagingParams) ([]GetMessagesPagingRow, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByLogin(ctx context.Context, login string) (User, error)
	IsUserChatMember(ctx context.Context, arg IsUserChatMemberParams) (bool, error)
	UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) error
	UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpsertEmailVerificationCode(ctx context.Context, arg UpsertEmailVerificationCodeParams) error
	UserWithEmailExists(ctx context.Context, email string) (bool, error)
	UserWithUsernameExists(ctx context.Context, username string) (bool, error)
}

var _ Querier = (*Queries)(nil)
