// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: friends.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createBlock = `-- name: CreateBlock :exec
INSERT INTO user_blocks (from_user_id, to_user_id)
VALUES ($1, $2)
`

type CreateBlockParams struct {
	FromUserID uuid.UUID `db:"from_user_id" json:"fromUserId"`
	ToUserID   uuid.UUID `db:"to_user_id" json:"toUserId"`
}

func (q *Queries) CreateBlock(ctx context.Context, arg CreateBlockParams) error {
	_, err := q.db.Exec(ctx, createBlock, arg.FromUserID, arg.ToUserID)
	return err
}

const createFriendRequest = `-- name: CreateFriendRequest :exec
INSERT INTO friend_requests (from_user_id, to_user_id, message)
VALUES ($1, $2, $3)
`

type CreateFriendRequestParams struct {
	FromUserID uuid.UUID `db:"from_user_id" json:"fromUserId"`
	ToUserID   uuid.UUID `db:"to_user_id" json:"toUserId"`
	Message    string    `db:"message" json:"message"`
}

func (q *Queries) CreateFriendRequest(ctx context.Context, arg CreateFriendRequestParams) error {
	_, err := q.db.Exec(ctx, createFriendRequest, arg.FromUserID, arg.ToUserID, arg.Message)
	return err
}

const deleteBlock = `-- name: DeleteBlock :exec
DELETE FROM user_blocks
WHERE from_user_id = $1 AND to_user_id = $2
`

type DeleteBlockParams struct {
	FromUserID uuid.UUID `db:"from_user_id" json:"fromUserId"`
	ToUserID   uuid.UUID `db:"to_user_id" json:"toUserId"`
}

func (q *Queries) DeleteBlock(ctx context.Context, arg DeleteBlockParams) error {
	_, err := q.db.Exec(ctx, deleteBlock, arg.FromUserID, arg.ToUserID)
	return err
}

const deleteFriendRequest = `-- name: DeleteFriendRequest :exec
DELETE FROM friend_requests
WHERE from_user_id = $1 AND to_user_id = $2
`

type DeleteFriendRequestParams struct {
	FromUserID uuid.UUID `db:"from_user_id" json:"fromUserId"`
	ToUserID   uuid.UUID `db:"to_user_id" json:"toUserId"`
}

func (q *Queries) DeleteFriendRequest(ctx context.Context, arg DeleteFriendRequestParams) error {
	_, err := q.db.Exec(ctx, deleteFriendRequest, arg.FromUserID, arg.ToUserID)
	return err
}

const deleteFriendshipEdge = `-- name: DeleteFriendshipEdge :exec
DELETE FROM friendships
WHERE user_id = $1 AND friend_id = $2
`

type DeleteFriendshipEdgeParams struct {
	UserID   uuid.UUID `db:"user_id" json:"userId"`
	FriendID uuid.UUID `db:"friend_id" json:"friendId"`
}

func (q *Queries) DeleteFriendshipEdge(ctx context.Context, arg DeleteFriendshipEdgeParams) error {
	_, err := q.db.Exec(ctx, deleteFriendshipEdge, arg.UserID, arg.FriendID)
	return err
}

const getFriendRequest = `-- name: GetFriendRequest :one
SELECT from_user_id, to_user_id, status, message, created_at, responded_at
FROM friend_requests
WHERE from_user_id = $1 AND to_user_id = $2
`

type GetFriendRequestParams struct {
	FromUserID uuid.UUID `db:"from_user_id" json:"fromUserId"`
	ToUserID   uuid.UUID `db:"to_user_id" json:"toUserId"`
}

func (q *Queries) GetFriendRequest(ctx context.Context, arg GetFriendRequestParams) (FriendRequest, error) {
	row := q.db.QueryRow(ctx, getFriendRequest, arg.FromUserID, arg.ToUserID)
	var i FriendRequest
	err := row.Scan(
		&i.FromUserID,
		&i.ToUserID,
		&i.Status,
		&i.Message,
		&i.CreatedAt,
		&i.RespondedAt,
	)
	return i, err
}

const insertFriendshipEdge = `-- name: InsertFriendshipEdge :exec
INSERT INTO friendships (user_id, friend_id, created_at)
VALUES ($1, $2, now())
`

type InsertFriendshipEdgeParams struct {
	UserID   uuid.UUID `db:"user_id" json:"userId"`
	FriendID uuid.UUID `db:"friend_id" json:"friendId"`
}

func (q *Queries) InsertFriendshipEdge(ctx context.Context, arg InsertFriendshipEdgeParams) error {
	_, err := q.db.Exec(ctx, insertFriendshipEdge, arg.UserID, arg.FriendID)
	return err
}

const isBlocked = `-- name: IsBlocked :one
SELECT EXISTS(
    SELECT 1 FROM user_blocks
    WHERE from_user_id = $1 AND to_user_id = $2
) AS blocked
`

type IsBlockedParams struct {
	FromUserID uuid.UUID `db:"from_user_id" json:"fromUserId"`
	ToUserID   uuid.UUID `db:"to_user_id" json:"toUserId"`
}

func (q *Queries) IsBlocked(ctx context.Context, arg IsBlockedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isBlocked, arg.FromUserID, arg.ToUserID)
	var blocked bool
	err := row.Scan(&blocked)
	return blocked, err
}

const listBlocked = `-- name: ListBlocked :many
SELECT from_user_id, to_user_id, created_at
FROM user_blocks
WHERE from_user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListBlocked(ctx context.Context, fromUserID uuid.UUID) ([]UserBlock, error) {
	rows, err := q.db.Query(ctx, listBlocked, fromUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserBlock{}
	for rows.Next() {
		var i UserBlock
		if err := rows.Scan(&i.FromUserID, &i.ToUserID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFriends = `-- name: ListFriends :many
SELECT user_id, friend_id, created_at
FROM friendships
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListFriends(ctx context.Context, userID uuid.UUID) ([]Friendship, error) {
	rows, err := q.db.Query(ctx, listFriends, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Friendship{}
	for rows.Next() {
		var i Friendship
		if err := rows.Scan(&i.UserID, &i.FriendID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncomingRequests = `-- name: ListIncomingRequests :many
SELECT from_user_id, to_user_id, status, message, created_at, responded_at
FROM friend_requests
WHERE to_user_id = $1 AND status = 'pending'
ORDER BY created_at DESC
`

func (q *Queries) ListIncomingRequests(ctx context.Context, toUserID uuid.UUID) ([]FriendRequest, error) {
	rows, err := q.db.Query(ctx, listIncomingRequests, toUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FriendRequest{}
	for rows.Next() {
		var i FriendRequest
		if err := rows.Scan(
			&i.FromUserID,
			&i.ToUserID,
			&i.Status,
			&i.Message,
			&i.CreatedAt,
			&i.RespondedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutgoingRequests = `-- name: ListOutgoingRequests :many
SELECT from_user_id, to_user_id, status, message, created_at, responded_at
FROM friend_requests
WHERE from_user_id = $1 AND status = 'pending'
ORDER BY created_at DESC
`

func (q *Queries) ListOutgoingRequests(ctx context.Context, fromUserID uuid.UUID) ([]FriendRequest, error) {
	rows, err := q.db.Query(ctx, listOutgoingRequests, fromUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FriendRequest{}
	for rows.Next() {
		var i FriendRequest
		if err := rows.Scan(
			&i.FromUserID,
			&i.ToUserID,
			&i.Status,
			&i.Message,
			&i.CreatedAt,
			&i.RespondedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
