// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type EmailVerificationCode struct {
	UserID       uuid.UUID          `db:"user_id" json:"userId"`
	CodeHash     string             `db:"code_hash" json:"codeHash"`
	ExpiresAt    pgtype.Timestamptz `db:"expires_at" json:"expiresAt"`
	Attempts     int32              `db:"attempts" json:"attempts"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	PendingEmail pgtype.Text        `db:"pending_email" json:"pendingEmail"`
}

type FriendRequest struct {
	FromUserID  uuid.UUID          `db:"from_user_id" json:"fromUserId"`
	ToUserID    uuid.UUID          `db:"to_user_id" json:"toUserId"`
	Status      string             `db:"status" json:"status"`
	Message     string             `db:"message" json:"message"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	RespondedAt pgtype.Timestamptz `db:"responded_at" json:"respondedAt"`
}

type Friendship struct {
	UserID    uuid.UUID          `db:"user_id" json:"userId"`
	FriendID  uuid.UUID          `db:"friend_id" json:"friendId"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}

type MemberRole struct {
	MemberID uuid.UUID `db:"member_id" json:"memberId"`
	RoleID   uuid.UUID `db:"role_id" json:"roleId"`
}

type Message struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	RoomID    uuid.UUID          `db:"room_id" json:"roomId"`
	SenderID  uuid.UUID          `db:"sender_id" json:"senderId"`
	Content   string             `db:"content" json:"content"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}

type Room struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Name      pgtype.Text        `db:"name" json:"name"`
	Slug      string             `db:"slug" json:"slug"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	ServerID  pgtype.UUID        `db:"server_id" json:"serverId"`
	Type      string             `db:"type" json:"type"`
	Position  int32              `db:"position" json:"position"`
}

type RoomMember struct {
	ID       uuid.UUID          `db:"id" json:"id"`
	RoomID   uuid.UUID          `db:"room_id" json:"roomId"`
	UserID   uuid.UUID          `db:"user_id" json:"userId"`
	JoinedAt pgtype.Timestamptz `db:"joined_at" json:"joinedAt"`
}

type Server struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	OwnerID   uuid.UUID          `db:"owner_id" json:"ownerId"`
	AvatarUrl pgtype.Text        `db:"avatar_url" json:"avatarUrl"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}

type ServerMember struct {
	ID       uuid.UUID          `db:"id" json:"id"`
	ServerID uuid.UUID          `db:"server_id" json:"serverId"`
	UserID   uuid.UUID          `db:"user_id" json:"userId"`
	Nickname pgtype.Text        `db:"nickname" json:"nickname"`
	JoinedAt pgtype.Timestamptz `db:"joined_at" json:"joinedAt"`
}

type ServerRole struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	ServerID    uuid.UUID          `db:"server_id" json:"serverId"`
	Name        string             `db:"name" json:"name"`
	Color       pgtype.Text        `db:"color" json:"color"`
	Permissions int64              `db:"permissions" json:"permissions"`
	Position    int32              `db:"position" json:"position"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}

type User struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	Username      string             `db:"username" json:"username"`
	Email         string             `db:"email" json:"email"`
	EmailVerified bool               `db:"email_verified" json:"emailVerified"`
	PasswordHash  pgtype.Text        `db:"password_hash" json:"passwordHash"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"createdAt"`
	AvatarUrl     pgtype.Text        `db:"avatar_url" json:"avatarUrl"`
}

type UserBlock struct {
	FromUserID uuid.UUID          `db:"from_user_id" json:"fromUserId"`
	ToUserID   uuid.UUID          `db:"to_user_id" json:"toUserId"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}
