// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: room.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addRoomMember = `-- name: AddRoomMember :exec
INSERT INTO room_members (id, room_id, user_id, joined_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (room_id, user_id) DO NOTHING
`

type AddRoomMemberParams struct {
	ID       uuid.UUID          `db:"id" json:"id"`
	RoomID   uuid.UUID          `db:"room_id" json:"roomId"`
	UserID   uuid.UUID          `db:"user_id" json:"userId"`
	JoinedAt pgtype.Timestamptz `db:"joined_at" json:"joinedAt"`
}

func (q *Queries) AddRoomMember(ctx context.Context, arg AddRoomMemberParams) error {
	_, err := q.db.Exec(ctx, addRoomMember,
		arg.ID,
		arg.RoomID,
		arg.UserID,
		arg.JoinedAt,
	)
	return err
}

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (id, name, slug, created_at)
VALUES ($1, $2, $3, $4)
RETURNING id, name, slug, created_at
`

type CreateRoomParams struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Name      pgtype.Text        `db:"name" json:"name"`
	Slug      string             `db:"slug" json:"slug"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (Room, error) {
	row := q.db.QueryRow(ctx, createRoom,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.CreatedAt,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const getRoom = `-- name: GetRoom :one
SELECT id, name, slug, created_at
FROM rooms
WHERE id = $1
`

func (q *Queries) GetRoom(ctx context.Context, id uuid.UUID) (Room, error) {
	row := q.db.QueryRow(ctx, getRoom, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
	)
	return i, err
}

const getUserRooms = `-- name: GetUserRooms :many
SELECT r.id, r.name, r.slug, r.created_at
FROM rooms r
         JOIN room_members rm ON rm.room_id = r.id
WHERE rm.user_id = $1
`

func (q *Queries) GetUserRooms(ctx context.Context, userID uuid.UUID) ([]Room, error) {
	rows, err := q.db.Query(ctx, getUserRooms, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isUserRoomMember = `-- name: IsUserRoomMember :one
SELECT EXISTS (SELECT 1
               FROM room_members
               WHERE room_id = $1
                 AND user_id = $2)
`

type IsUserRoomMemberParams struct {
	RoomID uuid.UUID `db:"room_id" json:"roomId"`
	UserID uuid.UUID `db:"user_id" json:"userId"`
}

func (q *Queries) IsUserRoomMember(ctx context.Context, arg IsUserRoomMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isUserRoomMember, arg.RoomID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const roomExists = `-- name: RoomExists :one
SELECT EXISTS (SELECT 1
               FROM rooms
               WHERE id = $1)
`

func (q *Queries) RoomExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, roomExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
