// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: server.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addServerMember = `-- name: AddServerMember :exec
INSERT INTO server_members (id, server_id, user_id, nickname, joined_at)
VALUES ($1, $2, $3, $4, $5)
`

type AddServerMemberParams struct {
	ID       uuid.UUID          `db:"id" json:"id"`
	ServerID uuid.UUID          `db:"server_id" json:"serverId"`
	UserID   uuid.UUID          `db:"user_id" json:"userId"`
	Nickname pgtype.Text        `db:"nickname" json:"nickname"`
	JoinedAt pgtype.Timestamptz `db:"joined_at" json:"joinedAt"`
}

func (q *Queries) AddServerMember(ctx context.Context, arg AddServerMemberParams) error {
	_, err := q.db.Exec(ctx, addServerMember,
		arg.ID,
		arg.ServerID,
		arg.UserID,
		arg.Nickname,
		arg.JoinedAt,
	)
	return err
}

const assignRoleToMember = `-- name: AssignRoleToMember :exec
INSERT INTO member_roles (member_id, role_id)
VALUES ($1, $2)
`

type AssignRoleToMemberParams struct {
	MemberID uuid.UUID `db:"member_id" json:"memberId"`
	RoleID   uuid.UUID `db:"role_id" json:"roleId"`
}

func (q *Queries) AssignRoleToMember(ctx context.Context, arg AssignRoleToMemberParams) error {
	_, err := q.db.Exec(ctx, assignRoleToMember, arg.MemberID, arg.RoleID)
	return err
}

const createChannel = `-- name: CreateChannel :one
INSERT INTO rooms (id, name, slug, server_id, type, position, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, slug, created_at, server_id, type, position
`

type CreateChannelParams struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Name      pgtype.Text        `db:"name" json:"name"`
	Slug      string             `db:"slug" json:"slug"`
	ServerID  pgtype.UUID        `db:"server_id" json:"serverId"`
	Type      string             `db:"type" json:"type"`
	Position  int32              `db:"position" json:"position"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Room, error) {
	row := q.db.QueryRow(ctx, createChannel,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.ServerID,
		arg.Type,
		arg.Position,
		arg.CreatedAt,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.CreatedAt,
		&i.ServerID,
		&i.Type,
		&i.Position,
	)
	return i, err
}

const createServer = `-- name: CreateServer :one
INSERT INTO servers (id, name, owner_id, avatar_url, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, owner_id, avatar_url, created_at
`

type CreateServerParams struct {
	ID        uuid.UUID          `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	OwnerID   uuid.UUID          `db:"owner_id" json:"ownerId"`
	AvatarUrl pgtype.Text        `db:"avatar_url" json:"avatarUrl"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}

func (q *Queries) CreateServer(ctx context.Context, arg CreateServerParams) (Server, error) {
	row := q.db.QueryRow(ctx, createServer,
		arg.ID,
		arg.Name,
		arg.OwnerID,
		arg.AvatarUrl,
		arg.CreatedAt,
	)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.AvatarUrl,
		&i.CreatedAt,
	)
	return i, err
}

const createServerRole = `-- name: CreateServerRole :one
INSERT INTO server_roles (id, server_id, name, color, permissions, position, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, server_id, name, color, permissions, position, created_at
`

type CreateServerRoleParams struct {
	ID          uuid.UUID          `db:"id" json:"id"`
	ServerID    uuid.UUID          `db:"server_id" json:"serverId"`
	Name        string             `db:"name" json:"name"`
	Color       pgtype.Text        `db:"color" json:"color"`
	Permissions int64              `db:"permissions" json:"permissions"`
	Position    int32              `db:"position" json:"position"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"createdAt"`
}

func (q *Queries) CreateServerRole(ctx context.Context, arg CreateServerRoleParams) (ServerRole, error) {
	row := q.db.QueryRow(ctx, createServerRole,
		arg.ID,
		arg.ServerID,
		arg.Name,
		arg.Color,
		arg.Permissions,
		arg.Position,
		arg.CreatedAt,
	)
	var i ServerRole
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.Name,
		&i.Color,
		&i.Permissions,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const deleteServer = `-- name: DeleteServer :exec
DELETE FROM servers WHERE id = $1
`

func (q *Queries) DeleteServer(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteServer, id)
	return err
}

const deleteServerRole = `-- name: DeleteServerRole :exec
DELETE FROM server_roles WHERE id = $1 AND server_id = $2
`

type DeleteServerRoleParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	ServerID uuid.UUID `db:"server_id" json:"serverId"`
}

func (q *Queries) DeleteServerRole(ctx context.Context, arg DeleteServerRoleParams) error {
	_, err := q.db.Exec(ctx, deleteServerRole, arg.ID, arg.ServerID)
	return err
}

const getMemberRoles = `-- name: GetMemberRoles :many
SELECT role_id FROM member_roles WHERE member_id = $1
`

func (q *Queries) GetMemberRoles(ctx context.Context, memberID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getMemberRoles, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var role_id uuid.UUID
		if err := rows.Scan(&role_id); err != nil {
			return nil, err
		}
		items = append(items, role_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServerByID = `-- name: GetServerByID :one
SELECT id, name, owner_id, avatar_url, created_at FROM servers WHERE id = $1
`

func (q *Queries) GetServerByID(ctx context.Context, id uuid.UUID) (Server, error) {
	row := q.db.QueryRow(ctx, getServerByID, id)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.AvatarUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getServerMember = `-- name: GetServerMember :one
SELECT sm.id, sm.server_id, sm.user_id, sm.nickname, sm.joined_at, u.username, u.email, u.email_verified, u.avatar_url as user_avatar_url
FROM server_members sm
JOIN users u ON sm.user_id = u.id
WHERE sm.server_id = $1 AND sm.user_id = $2
`

type GetServerMemberParams struct {
	ServerID uuid.UUID `db:"server_id" json:"serverId"`
	UserID   uuid.UUID `db:"user_id" json:"userId"`
}

type GetServerMemberRow struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	ServerID      uuid.UUID          `db:"server_id" json:"serverId"`
	UserID        uuid.UUID          `db:"user_id" json:"userId"`
	Nickname      pgtype.Text        `db:"nickname" json:"nickname"`
	JoinedAt      pgtype.Timestamptz `db:"joined_at" json:"joinedAt"`
	Username      string             `db:"username" json:"username"`
	Email         string             `db:"email" json:"email"`
	EmailVerified bool               `db:"email_verified" json:"emailVerified"`
	UserAvatarUrl pgtype.Text        `db:"user_avatar_url" json:"userAvatarUrl"`
}

func (q *Queries) GetServerMember(ctx context.Context, arg GetServerMemberParams) (GetServerMemberRow, error) {
	row := q.db.QueryRow(ctx, getServerMember, arg.ServerID, arg.UserID)
	var i GetServerMemberRow
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.UserID,
		&i.Nickname,
		&i.JoinedAt,
		&i.Username,
		&i.Email,
		&i.EmailVerified,
		&i.UserAvatarUrl,
	)
	return i, err
}

const listServerChannels = `-- name: ListServerChannels :many
SELECT id, name, slug, created_at, server_id, type, position FROM rooms WHERE server_id = $1 ORDER BY position ASC, created_at ASC
`

func (q *Queries) ListServerChannels(ctx context.Context, serverID pgtype.UUID) ([]Room, error) {
	rows, err := q.db.Query(ctx, listServerChannels, serverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Room{}
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.CreatedAt,
			&i.ServerID,
			&i.Type,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServerMembers = `-- name: ListServerMembers :many
SELECT sm.id, sm.server_id, sm.user_id, sm.nickname, sm.joined_at, u.username, u.avatar_url as user_avatar_url
FROM server_members sm
JOIN users u ON sm.user_id = u.id
WHERE sm.server_id = $1
ORDER BY sm.joined_at ASC
`

type ListServerMembersRow struct {
	ID            uuid.UUID          `db:"id" json:"id"`
	ServerID      uuid.UUID          `db:"server_id" json:"serverId"`
	UserID        uuid.UUID          `db:"user_id" json:"userId"`
	Nickname      pgtype.Text        `db:"nickname" json:"nickname"`
	JoinedAt      pgtype.Timestamptz `db:"joined_at" json:"joinedAt"`
	Username      string             `db:"username" json:"username"`
	UserAvatarUrl pgtype.Text        `db:"user_avatar_url" json:"userAvatarUrl"`
}

func (q *Queries) ListServerMembers(ctx context.Context, serverID uuid.UUID) ([]ListServerMembersRow, error) {
	rows, err := q.db.Query(ctx, listServerMembers, serverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServerMembersRow{}
	for rows.Next() {
		var i ListServerMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.UserID,
			&i.Nickname,
			&i.JoinedAt,
			&i.Username,
			&i.UserAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServerRoles = `-- name: ListServerRoles :many
SELECT id, server_id, name, color, permissions, position, created_at FROM server_roles WHERE server_id = $1 ORDER BY position ASC
`

func (q *Queries) ListServerRoles(ctx context.Context, serverID uuid.UUID) ([]ServerRole, error) {
	rows, err := q.db.Query(ctx, listServerRoles, serverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ServerRole{}
	for rows.Next() {
		var i ServerRole
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.Name,
			&i.Color,
			&i.Permissions,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRoleFromMember = `-- name: RemoveRoleFromMember :exec
DELETE FROM member_roles WHERE member_id = $1 AND role_id = $2
`

type RemoveRoleFromMemberParams struct {
	MemberID uuid.UUID `db:"member_id" json:"memberId"`
	RoleID   uuid.UUID `db:"role_id" json:"roleId"`
}

func (q *Queries) RemoveRoleFromMember(ctx context.Context, arg RemoveRoleFromMemberParams) error {
	_, err := q.db.Exec(ctx, removeRoleFromMember, arg.MemberID, arg.RoleID)
	return err
}

const removeServerMember = `-- name: RemoveServerMember :exec
DELETE FROM server_members WHERE server_id = $1 AND user_id = $2
`

type RemoveServerMemberParams struct {
	ServerID uuid.UUID `db:"server_id" json:"serverId"`
	UserID   uuid.UUID `db:"user_id" json:"userId"`
}

func (q *Queries) RemoveServerMember(ctx context.Context, arg RemoveServerMemberParams) error {
	_, err := q.db.Exec(ctx, removeServerMember, arg.ServerID, arg.UserID)
	return err
}

const updateServerMemberNickname = `-- name: UpdateServerMemberNickname :exec
UPDATE server_members SET nickname = $3 WHERE server_id = $1 AND user_id = $2
`

type UpdateServerMemberNicknameParams struct {
	ServerID uuid.UUID   `db:"server_id" json:"serverId"`
	UserID   uuid.UUID   `db:"user_id" json:"userId"`
	Nickname pgtype.Text `db:"nickname" json:"nickname"`
}

func (q *Queries) UpdateServerMemberNickname(ctx context.Context, arg UpdateServerMemberNicknameParams) error {
	_, err := q.db.Exec(ctx, updateServerMemberNickname, arg.ServerID, arg.UserID, arg.Nickname)
	return err
}

const updateServerRole = `-- name: UpdateServerRole :one
UPDATE server_roles
SET name = $3, color = $4, permissions = $5, position = $6
WHERE id = $1 AND server_id = $2
RETURNING id, server_id, name, color, permissions, position, created_at
`

type UpdateServerRoleParams struct {
	ID          uuid.UUID   `db:"id" json:"id"`
	ServerID    uuid.UUID   `db:"server_id" json:"serverId"`
	Name        string      `db:"name" json:"name"`
	Color       pgtype.Text `db:"color" json:"color"`
	Permissions int64       `db:"permissions" json:"permissions"`
	Position    int32       `db:"position" json:"position"`
}

func (q *Queries) UpdateServerRole(ctx context.Context, arg UpdateServerRoleParams) (ServerRole, error) {
	row := q.db.QueryRow(ctx, updateServerRole,
		arg.ID,
		arg.ServerID,
		arg.Name,
		arg.Color,
		arg.Permissions,
		arg.Position,
	)
	var i ServerRole
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.Name,
		&i.Color,
		&i.Permissions,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}
