/* tslint:disable */
/* eslint-disable */
/**
 * Lunar API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface AuthLoginCredentials {
    'login': string;
    'password': string;
}
export interface AuthRegisterCredentials {
    'confirmPassword': string;
    'email': string;
    'password': string;
    'username': string;
}
export interface AuthResendVerificationCodeRequest {
    'email': string;
}
export interface AuthTokens {
    'accessToken': string;
    'refreshToken': string;
}
export interface AuthVerifyEmailRequest {
    'code': string;
    'email': string;
}
export interface CallStartCallRequest {
    'callee_id': string;
}
export interface CallStartCallResponse {
    'room_name'?: string;
    'token'?: string;
}
export interface HttputilErrorBody {
    'code'?: string;
    'fields'?: object;
    'message'?: string;
}
export interface HttputilErrorResponse {
    'error'?: HttputilErrorBody;
}
export interface LivekitTokenResponse {
    'token': string;
}
export interface MessageGetPagingResponse {
    'messages'?: Array<ModelMessage>;
    'nextCursor'?: string;
}
export interface ModelMessage {
    'content': string;
    'createdAt': string;
    'id': string;
    'roomID': string;
    'sender': ModelMessageSender;
}
export interface ModelMessageSender {
    'avatarUrl'?: string;
    'id'?: string;
    'username'?: string;
}
export interface ModelRoom {
    'id': string;
    'members'?: Array<ModelRoomMember>;
    'name'?: string;
    'slug': string;
}
export interface ModelRoomMember {
    'id': string;
    'roomID': string;
    'userID': string;
}
export interface ModelUser {
    'avatarUrl'?: string;
    'email': string;
    'emailVerified': boolean;
    'id': string;
    'username': string;
}
export interface RoomCreateRequest {
    'name'?: string;
}
export interface RoomCreateResponse {
    'slug': string;
}
export interface RoomListResponse {
    'rooms': Array<ModelRoom>;
}
export interface UserUpdateEmailRequest {
    'email': string;
}
export interface UserUpdatePasswordRequest {
    'currentPassword': string;
    'newPassword': string;
}

/**
 * AuthApi - axios parameter creator
 */
export const AuthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Login a user
         * @param {AuthLoginCredentials} input Login credentials
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authLoginPost: async (input: AuthLoginCredentials, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'input' is not null or undefined
            assertParamExists('authLoginPost', 'input', input)
            const localVarPath = `/auth/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(input, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Logout a user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authLogoutPost: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/logout`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Refresh access token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authRefreshPost: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/refresh`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Register a new user
         * @param {AuthRegisterCredentials} input Registration credentials
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authRegisterPost: async (input: AuthRegisterCredentials, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'input' is not null or undefined
            assertParamExists('authRegisterPost', 'input', input)
            const localVarPath = `/auth/register`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(input, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Verify email
         * @param {AuthVerifyEmailRequest} input Verification credentials
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authVerifyPost: async (input: AuthVerifyEmailRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'input' is not null or undefined
            assertParamExists('authVerifyPost', 'input', input)
            const localVarPath = `/auth/verify`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(input, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Resend verification code
         * @param {AuthResendVerificationCodeRequest} input Email
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authVerifyResendPost: async (input: AuthResendVerificationCodeRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'input' is not null or undefined
            assertParamExists('authVerifyResendPost', 'input', input)
            const localVarPath = `/auth/verify/resend`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(input, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthApi - functional programming interface
 */
export const AuthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Login a user
         * @param {AuthLoginCredentials} input Login credentials
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authLoginPost(input: AuthLoginCredentials, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AuthTokens>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authLoginPost(input, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authLoginPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Logout a user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authLogoutPost(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authLogoutPost(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authLogoutPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Refresh access token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authRefreshPost(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AuthTokens>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authRefreshPost(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authRefreshPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Register a new user
         * @param {AuthRegisterCredentials} input Registration credentials
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authRegisterPost(input: AuthRegisterCredentials, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authRegisterPost(input, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authRegisterPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Verify email
         * @param {AuthVerifyEmailRequest} input Verification credentials
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authVerifyPost(input: AuthVerifyEmailRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authVerifyPost(input, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authVerifyPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Resend verification code
         * @param {AuthResendVerificationCodeRequest} input Email
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authVerifyResendPost(input: AuthResendVerificationCodeRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authVerifyResendPost(input, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authVerifyResendPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuthApi - factory interface
 */
export const AuthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthApiFp(configuration)
    return {
        /**
         * 
         * @summary Login a user
         * @param {AuthLoginCredentials} input Login credentials
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authLoginPost(input: AuthLoginCredentials, options?: RawAxiosRequestConfig): AxiosPromise<AuthTokens> {
            return localVarFp.authLoginPost(input, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Logout a user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authLogoutPost(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.authLogoutPost(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Refresh access token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authRefreshPost(options?: RawAxiosRequestConfig): AxiosPromise<AuthTokens> {
            return localVarFp.authRefreshPost(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Register a new user
         * @param {AuthRegisterCredentials} input Registration credentials
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authRegisterPost(input: AuthRegisterCredentials, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.authRegisterPost(input, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Verify email
         * @param {AuthVerifyEmailRequest} input Verification credentials
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authVerifyPost(input: AuthVerifyEmailRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.authVerifyPost(input, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Resend verification code
         * @param {AuthResendVerificationCodeRequest} input Email
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authVerifyResendPost(input: AuthResendVerificationCodeRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.authVerifyResendPost(input, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthApi - object-oriented interface
 */
export class AuthApi extends BaseAPI {
    /**
     * 
     * @summary Login a user
     * @param {AuthLoginCredentials} input Login credentials
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public authLoginPost(input: AuthLoginCredentials, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authLoginPost(input, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Logout a user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public authLogoutPost(options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authLogoutPost(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Refresh access token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public authRefreshPost(options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authRefreshPost(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Register a new user
     * @param {AuthRegisterCredentials} input Registration credentials
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public authRegisterPost(input: AuthRegisterCredentials, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authRegisterPost(input, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Verify email
     * @param {AuthVerifyEmailRequest} input Verification credentials
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public authVerifyPost(input: AuthVerifyEmailRequest, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authVerifyPost(input, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Resend verification code
     * @param {AuthResendVerificationCodeRequest} input Email
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public authVerifyResendPost(input: AuthResendVerificationCodeRequest, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authVerifyResendPost(input, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * CallApi - axios parameter creator
 */
export const CallApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Start a direct call
         * @param {CallStartCallRequest} input Call params
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        callStartPost: async (input: CallStartCallRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'input' is not null or undefined
            assertParamExists('callStartPost', 'input', input)
            const localVarPath = `/call/start`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(input, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CallApi - functional programming interface
 */
export const CallApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CallApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Start a direct call
         * @param {CallStartCallRequest} input Call params
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async callStartPost(input: CallStartCallRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CallStartCallResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.callStartPost(input, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CallApi.callStartPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CallApi - factory interface
 */
export const CallApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CallApiFp(configuration)
    return {
        /**
         * 
         * @summary Start a direct call
         * @param {CallStartCallRequest} input Call params
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        callStartPost(input: CallStartCallRequest, options?: RawAxiosRequestConfig): AxiosPromise<CallStartCallResponse> {
            return localVarFp.callStartPost(input, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CallApi - object-oriented interface
 */
export class CallApi extends BaseAPI {
    /**
     * 
     * @summary Start a direct call
     * @param {CallStartCallRequest} input Call params
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public callStartPost(input: CallStartCallRequest, options?: RawAxiosRequestConfig) {
        return CallApiFp(this.configuration).callStartPost(input, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * LivekitApi - axios parameter creator
 */
export const LivekitApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get livekit access token
         * @param {string} roomSlug Room Slug
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        livekitTokenRoomSlugGet: async (roomSlug: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'roomSlug' is not null or undefined
            assertParamExists('livekitTokenRoomSlugGet', 'roomSlug', roomSlug)
            const localVarPath = `/livekit/token/{roomSlug}`
                .replace(`{${"roomSlug"}}`, encodeURIComponent(String(roomSlug)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * LivekitApi - functional programming interface
 */
export const LivekitApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = LivekitApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get livekit access token
         * @param {string} roomSlug Room Slug
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async livekitTokenRoomSlugGet(roomSlug: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LivekitTokenResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.livekitTokenRoomSlugGet(roomSlug, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LivekitApi.livekitTokenRoomSlugGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * LivekitApi - factory interface
 */
export const LivekitApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = LivekitApiFp(configuration)
    return {
        /**
         * 
         * @summary Get livekit access token
         * @param {string} roomSlug Room Slug
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        livekitTokenRoomSlugGet(roomSlug: string, options?: RawAxiosRequestConfig): AxiosPromise<LivekitTokenResponse> {
            return localVarFp.livekitTokenRoomSlugGet(roomSlug, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * LivekitApi - object-oriented interface
 */
export class LivekitApi extends BaseAPI {
    /**
     * 
     * @summary Get livekit access token
     * @param {string} roomSlug Room Slug
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public livekitTokenRoomSlugGet(roomSlug: string, options?: RawAxiosRequestConfig) {
        return LivekitApiFp(this.configuration).livekitTokenRoomSlugGet(roomSlug, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * MessageApi - axios parameter creator
 */
export const MessageApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary List messages in a room
         * @param {string} roomSlug Room Slug
         * @param {number} [limit] Limit
         * @param {string} [cursor] Cursor
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        roomsRoomSlugMessagesGet: async (roomSlug: string, limit?: number, cursor?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'roomSlug' is not null or undefined
            assertParamExists('roomsRoomSlugMessagesGet', 'roomSlug', roomSlug)
            const localVarPath = `/rooms/{roomSlug}/messages`
                .replace(`{${"roomSlug"}}`, encodeURIComponent(String(roomSlug)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (cursor !== undefined) {
                localVarQueryParameter['cursor'] = cursor;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MessageApi - functional programming interface
 */
export const MessageApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MessageApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary List messages in a room
         * @param {string} roomSlug Room Slug
         * @param {number} [limit] Limit
         * @param {string} [cursor] Cursor
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async roomsRoomSlugMessagesGet(roomSlug: string, limit?: number, cursor?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MessageGetPagingResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.roomsRoomSlugMessagesGet(roomSlug, limit, cursor, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MessageApi.roomsRoomSlugMessagesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * MessageApi - factory interface
 */
export const MessageApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MessageApiFp(configuration)
    return {
        /**
         * 
         * @summary List messages in a room
         * @param {string} roomSlug Room Slug
         * @param {number} [limit] Limit
         * @param {string} [cursor] Cursor
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        roomsRoomSlugMessagesGet(roomSlug: string, limit?: number, cursor?: string, options?: RawAxiosRequestConfig): AxiosPromise<MessageGetPagingResponse> {
            return localVarFp.roomsRoomSlugMessagesGet(roomSlug, limit, cursor, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MessageApi - object-oriented interface
 */
export class MessageApi extends BaseAPI {
    /**
     * 
     * @summary List messages in a room
     * @param {string} roomSlug Room Slug
     * @param {number} [limit] Limit
     * @param {string} [cursor] Cursor
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public roomsRoomSlugMessagesGet(roomSlug: string, limit?: number, cursor?: string, options?: RawAxiosRequestConfig) {
        return MessageApiFp(this.configuration).roomsRoomSlugMessagesGet(roomSlug, limit, cursor, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * RoomApi - axios parameter creator
 */
export const RoomApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary List user rooms
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        roomsGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/rooms`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create a new room
         * @param {RoomCreateRequest} input Room creation params
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        roomsPost: async (input: RoomCreateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'input' is not null or undefined
            assertParamExists('roomsPost', 'input', input)
            const localVarPath = `/rooms`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(input, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Join current user to room
         * @param {string} roomSlug Room Slug
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        roomsRoomSlugPost: async (roomSlug: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'roomSlug' is not null or undefined
            assertParamExists('roomsRoomSlugPost', 'roomSlug', roomSlug)
            const localVarPath = `/rooms/{roomSlug}`
                .replace(`{${"roomSlug"}}`, encodeURIComponent(String(roomSlug)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RoomApi - functional programming interface
 */
export const RoomApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RoomApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary List user rooms
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async roomsGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RoomListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.roomsGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RoomApi.roomsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Create a new room
         * @param {RoomCreateRequest} input Room creation params
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async roomsPost(input: RoomCreateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RoomCreateResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.roomsPost(input, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RoomApi.roomsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Join current user to room
         * @param {string} roomSlug Room Slug
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async roomsRoomSlugPost(roomSlug: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.roomsRoomSlugPost(roomSlug, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RoomApi.roomsRoomSlugPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * RoomApi - factory interface
 */
export const RoomApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RoomApiFp(configuration)
    return {
        /**
         * 
         * @summary List user rooms
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        roomsGet(options?: RawAxiosRequestConfig): AxiosPromise<RoomListResponse> {
            return localVarFp.roomsGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create a new room
         * @param {RoomCreateRequest} input Room creation params
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        roomsPost(input: RoomCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<RoomCreateResponse> {
            return localVarFp.roomsPost(input, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Join current user to room
         * @param {string} roomSlug Room Slug
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        roomsRoomSlugPost(roomSlug: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.roomsRoomSlugPost(roomSlug, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RoomApi - object-oriented interface
 */
export class RoomApi extends BaseAPI {
    /**
     * 
     * @summary List user rooms
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public roomsGet(options?: RawAxiosRequestConfig) {
        return RoomApiFp(this.configuration).roomsGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create a new room
     * @param {RoomCreateRequest} input Room creation params
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public roomsPost(input: RoomCreateRequest, options?: RawAxiosRequestConfig) {
        return RoomApiFp(this.configuration).roomsPost(input, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Join current user to room
     * @param {string} roomSlug Room Slug
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public roomsRoomSlugPost(roomSlug: string, options?: RawAxiosRequestConfig) {
        return RoomApiFp(this.configuration).roomsRoomSlugPost(roomSlug, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * UserApi - axios parameter creator
 */
export const UserApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Upload user avatar
         * @param {File} avatar Avatar file
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersMeAvatarPost: async (avatar: File, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'avatar' is not null or undefined
            assertParamExists('usersMeAvatarPost', 'avatar', avatar)
            const localVarPath = `/users/me/avatar`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


            if (avatar !== undefined) { 
                localVarFormParams.append('avatar', avatar as any);
            }
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update user email
         * @param {UserUpdateEmailRequest} input Email update request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersMeEmailPut: async (input: UserUpdateEmailRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'input' is not null or undefined
            assertParamExists('usersMeEmailPut', 'input', input)
            const localVarPath = `/users/me/email`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(input, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get current user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersMeGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/me`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Change user password
         * @param {UserUpdatePasswordRequest} input Password change request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersMePasswordPut: async (input: UserUpdatePasswordRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'input' is not null or undefined
            assertParamExists('usersMePasswordPut', 'input', input)
            const localVarPath = `/users/me/password`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(input, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserApi - functional programming interface
 */
export const UserApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UserApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Upload user avatar
         * @param {File} avatar Avatar file
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersMeAvatarPost(avatar: File, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersMeAvatarPost(avatar, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.usersMeAvatarPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update user email
         * @param {UserUpdateEmailRequest} input Email update request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersMeEmailPut(input: UserUpdateEmailRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersMeEmailPut(input, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.usersMeEmailPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get current user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersMeGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ModelUser>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersMeGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.usersMeGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Change user password
         * @param {UserUpdatePasswordRequest} input Password change request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersMePasswordPut(input: UserUpdatePasswordRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersMePasswordPut(input, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.usersMePasswordPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UserApi - factory interface
 */
export const UserApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UserApiFp(configuration)
    return {
        /**
         * 
         * @summary Upload user avatar
         * @param {File} avatar Avatar file
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersMeAvatarPost(avatar: File, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.usersMeAvatarPost(avatar, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update user email
         * @param {UserUpdateEmailRequest} input Email update request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersMeEmailPut(input: UserUpdateEmailRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.usersMeEmailPut(input, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get current user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersMeGet(options?: RawAxiosRequestConfig): AxiosPromise<ModelUser> {
            return localVarFp.usersMeGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Change user password
         * @param {UserUpdatePasswordRequest} input Password change request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersMePasswordPut(input: UserUpdatePasswordRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.usersMePasswordPut(input, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UserApi - object-oriented interface
 */
export class UserApi extends BaseAPI {
    /**
     * 
     * @summary Upload user avatar
     * @param {File} avatar Avatar file
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public usersMeAvatarPost(avatar: File, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).usersMeAvatarPost(avatar, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update user email
     * @param {UserUpdateEmailRequest} input Email update request
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public usersMeEmailPut(input: UserUpdateEmailRequest, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).usersMeEmailPut(input, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get current user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public usersMeGet(options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).usersMeGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Change user password
     * @param {UserUpdatePasswordRequest} input Password change request
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public usersMePasswordPut(input: UserUpdatePasswordRequest, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).usersMePasswordPut(input, options).then((request) => request(this.axios, this.basePath));
    }
}



