/* tslint:disable */
/* eslint-disable */
/**
 * Lunar API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface AuthLoginCredentials {
    'login': string;
    'password': string;
}
export interface AuthRegisterCredentials {
    'confirmPassword': string;
    'email': string;
    'password': string;
    'username': string;
}
export interface AuthTokens {
    'accessToken': string;
    'refreshToken': string;
}
export interface ChatCreateRequest {
    'name'?: string;
    'type': string;
}
export interface ChatCreateResponse {
    'id': string;
}
export interface ChatListResponse {
    'chats': Array<ModelChat>;
}
export interface HttputilErrorBody {
    'code'?: string;
    'fields'?: object;
    'message'?: string;
}
export interface HttputilErrorResponse {
    'error'?: HttputilErrorBody;
}
export interface MessageGetPagingResponse {
    'messages'?: Array<ModelMessage>;
    'nextCursor'?: string;
}
export interface ModelChat {
    'id': string;
    'name'?: string;
    'type': string;
}
export interface ModelMessage {
    'chatId': string;
    'content': string;
    'createdAt': string;
    'id': string;
    'sender': ModelUser;
}
export interface ModelUser {
    'avatarUrl': string;
    'email': string;
    'emailVerified': boolean;
    'id': string;
    'username': string;
}
export interface UserSendVerificationCodeRequest {
    'email': string;
}
export interface UserUpdateEmailRequest {
    'email': string;
}
export interface UserUpdatePasswordRequest {
    'currentPassword': string;
    'newPassword': string;
}

/**
 * AuthApi - axios parameter creator
 */
export const AuthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Login a user
         * @param {AuthLoginCredentials} input Login credentials
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authLoginPost: async (input: AuthLoginCredentials, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'input' is not null or undefined
            assertParamExists('authLoginPost', 'input', input)
            const localVarPath = `/auth/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(input, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Logout a user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authLogoutPost: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/logout`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Refresh access token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authRefreshPost: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/refresh`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Register a new user
         * @param {AuthRegisterCredentials} input Registration credentials
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authRegisterPost: async (input: AuthRegisterCredentials, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'input' is not null or undefined
            assertParamExists('authRegisterPost', 'input', input)
            const localVarPath = `/auth/register`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(input, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthApi - functional programming interface
 */
export const AuthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Login a user
         * @param {AuthLoginCredentials} input Login credentials
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authLoginPost(input: AuthLoginCredentials, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AuthTokens>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authLoginPost(input, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authLoginPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Logout a user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authLogoutPost(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authLogoutPost(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authLogoutPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Refresh access token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authRefreshPost(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AuthTokens>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authRefreshPost(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authRefreshPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Register a new user
         * @param {AuthRegisterCredentials} input Registration credentials
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authRegisterPost(input: AuthRegisterCredentials, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AuthTokens>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authRegisterPost(input, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.authRegisterPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuthApi - factory interface
 */
export const AuthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthApiFp(configuration)
    return {
        /**
         * 
         * @summary Login a user
         * @param {AuthLoginCredentials} input Login credentials
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authLoginPost(input: AuthLoginCredentials, options?: RawAxiosRequestConfig): AxiosPromise<AuthTokens> {
            return localVarFp.authLoginPost(input, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Logout a user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authLogoutPost(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.authLogoutPost(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Refresh access token
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authRefreshPost(options?: RawAxiosRequestConfig): AxiosPromise<AuthTokens> {
            return localVarFp.authRefreshPost(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Register a new user
         * @param {AuthRegisterCredentials} input Registration credentials
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authRegisterPost(input: AuthRegisterCredentials, options?: RawAxiosRequestConfig): AxiosPromise<AuthTokens> {
            return localVarFp.authRegisterPost(input, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthApi - object-oriented interface
 */
export class AuthApi extends BaseAPI {
    /**
     * 
     * @summary Login a user
     * @param {AuthLoginCredentials} input Login credentials
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public authLoginPost(input: AuthLoginCredentials, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authLoginPost(input, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Logout a user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public authLogoutPost(options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authLogoutPost(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Refresh access token
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public authRefreshPost(options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authRefreshPost(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Register a new user
     * @param {AuthRegisterCredentials} input Registration credentials
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public authRegisterPost(input: AuthRegisterCredentials, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).authRegisterPost(input, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * ChatApi - axios parameter creator
 */
export const ChatApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Join current user to chat
         * @param {string} chatID Chat ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        chatsChatIDPost: async (chatID: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'chatID' is not null or undefined
            assertParamExists('chatsChatIDPost', 'chatID', chatID)
            const localVarPath = `/chats/{chatID}`
                .replace(`{${"chatID"}}`, encodeURIComponent(String(chatID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Connect to the websocket to receive real-time notifications in a chat
         * @summary Connect to the websocket in a chat
         * @param {string} chatID Chat ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        chatsChatIDWsGet: async (chatID: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'chatID' is not null or undefined
            assertParamExists('chatsChatIDWsGet', 'chatID', chatID)
            const localVarPath = `/chats/{chatID}/ws`
                .replace(`{${"chatID"}}`, encodeURIComponent(String(chatID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication WebSocketQueryAuth required
            await setApiKeyToObject(localVarQueryParameter, "token", configuration)

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List user chats
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        chatsGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/chats`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Accept'] = '*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Create a new chat
         * @param {ChatCreateRequest} input Chat creation params
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        chatsPost: async (input: ChatCreateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'input' is not null or undefined
            assertParamExists('chatsPost', 'input', input)
            const localVarPath = `/chats`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(input, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ChatApi - functional programming interface
 */
export const ChatApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ChatApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Join current user to chat
         * @param {string} chatID Chat ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async chatsChatIDPost(chatID: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.chatsChatIDPost(chatID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ChatApi.chatsChatIDPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Connect to the websocket to receive real-time notifications in a chat
         * @summary Connect to the websocket in a chat
         * @param {string} chatID Chat ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async chatsChatIDWsGet(chatID: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.chatsChatIDWsGet(chatID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ChatApi.chatsChatIDWsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List user chats
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async chatsGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ChatListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.chatsGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ChatApi.chatsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Create a new chat
         * @param {ChatCreateRequest} input Chat creation params
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async chatsPost(input: ChatCreateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ChatCreateResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.chatsPost(input, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ChatApi.chatsPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ChatApi - factory interface
 */
export const ChatApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ChatApiFp(configuration)
    return {
        /**
         * 
         * @summary Join current user to chat
         * @param {string} chatID Chat ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        chatsChatIDPost(chatID: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.chatsChatIDPost(chatID, options).then((request) => request(axios, basePath));
        },
        /**
         * Connect to the websocket to receive real-time notifications in a chat
         * @summary Connect to the websocket in a chat
         * @param {string} chatID Chat ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        chatsChatIDWsGet(chatID: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.chatsChatIDWsGet(chatID, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List user chats
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        chatsGet(options?: RawAxiosRequestConfig): AxiosPromise<ChatListResponse> {
            return localVarFp.chatsGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Create a new chat
         * @param {ChatCreateRequest} input Chat creation params
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        chatsPost(input: ChatCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<ChatCreateResponse> {
            return localVarFp.chatsPost(input, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ChatApi - object-oriented interface
 */
export class ChatApi extends BaseAPI {
    /**
     * 
     * @summary Join current user to chat
     * @param {string} chatID Chat ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public chatsChatIDPost(chatID: string, options?: RawAxiosRequestConfig) {
        return ChatApiFp(this.configuration).chatsChatIDPost(chatID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Connect to the websocket to receive real-time notifications in a chat
     * @summary Connect to the websocket in a chat
     * @param {string} chatID Chat ID
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public chatsChatIDWsGet(chatID: string, options?: RawAxiosRequestConfig) {
        return ChatApiFp(this.configuration).chatsChatIDWsGet(chatID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List user chats
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public chatsGet(options?: RawAxiosRequestConfig) {
        return ChatApiFp(this.configuration).chatsGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Create a new chat
     * @param {ChatCreateRequest} input Chat creation params
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public chatsPost(input: ChatCreateRequest, options?: RawAxiosRequestConfig) {
        return ChatApiFp(this.configuration).chatsPost(input, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * MessageApi - axios parameter creator
 */
export const MessageApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary List messages in a chat
         * @param {string} chatID Chat ID
         * @param {number} [limit] Limit
         * @param {string} [cursor] Cursor
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        chatsChatIDMessagesGet: async (chatID: string, limit?: number, cursor?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'chatID' is not null or undefined
            assertParamExists('chatsChatIDMessagesGet', 'chatID', chatID)
            const localVarPath = `/chats/{chatID}/messages`
                .replace(`{${"chatID"}}`, encodeURIComponent(String(chatID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (cursor !== undefined) {
                localVarQueryParameter['cursor'] = cursor;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MessageApi - functional programming interface
 */
export const MessageApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MessageApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary List messages in a chat
         * @param {string} chatID Chat ID
         * @param {number} [limit] Limit
         * @param {string} [cursor] Cursor
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async chatsChatIDMessagesGet(chatID: string, limit?: number, cursor?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MessageGetPagingResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.chatsChatIDMessagesGet(chatID, limit, cursor, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MessageApi.chatsChatIDMessagesGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * MessageApi - factory interface
 */
export const MessageApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MessageApiFp(configuration)
    return {
        /**
         * 
         * @summary List messages in a chat
         * @param {string} chatID Chat ID
         * @param {number} [limit] Limit
         * @param {string} [cursor] Cursor
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        chatsChatIDMessagesGet(chatID: string, limit?: number, cursor?: string, options?: RawAxiosRequestConfig): AxiosPromise<MessageGetPagingResponse> {
            return localVarFp.chatsChatIDMessagesGet(chatID, limit, cursor, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MessageApi - object-oriented interface
 */
export class MessageApi extends BaseAPI {
    /**
     * 
     * @summary List messages in a chat
     * @param {string} chatID Chat ID
     * @param {number} [limit] Limit
     * @param {string} [cursor] Cursor
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public chatsChatIDMessagesGet(chatID: string, limit?: number, cursor?: string, options?: RawAxiosRequestConfig) {
        return MessageApiFp(this.configuration).chatsChatIDMessagesGet(chatID, limit, cursor, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * UserApi - axios parameter creator
 */
export const UserApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Upload user avatar
         * @param {File} avatar Avatar file
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersMeAvatarPost: async (avatar: File, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'avatar' is not null or undefined
            assertParamExists('usersMeAvatarPost', 'avatar', avatar)
            const localVarPath = `/users/me/avatar`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)


            if (avatar !== undefined) { 
                localVarFormParams.append('avatar', avatar as any);
            }
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update user email
         * @param {UserUpdateEmailRequest} input Email update request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersMeEmailPut: async (input: UserUpdateEmailRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'input' is not null or undefined
            assertParamExists('usersMeEmailPut', 'input', input)
            const localVarPath = `/users/me/email`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(input, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get current user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersMeGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/users/me`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Change user password
         * @param {UserUpdatePasswordRequest} input Password change request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersMePasswordPut: async (input: UserUpdatePasswordRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'input' is not null or undefined
            assertParamExists('usersMePasswordPut', 'input', input)
            const localVarPath = `/users/me/password`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(input, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Send verification code
         * @param {UserSendVerificationCodeRequest} input Verification request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersMeVerificationCodePost: async (input: UserSendVerificationCodeRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'input' is not null or undefined
            assertParamExists('usersMeVerificationCodePost', 'input', input)
            const localVarPath = `/users/me/verification-code`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication BearerAuth required
            await setApiKeyToObject(localVarHeaderParameter, "Authorization", configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(input, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserApi - functional programming interface
 */
export const UserApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UserApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Upload user avatar
         * @param {File} avatar Avatar file
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersMeAvatarPost(avatar: File, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersMeAvatarPost(avatar, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.usersMeAvatarPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update user email
         * @param {UserUpdateEmailRequest} input Email update request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersMeEmailPut(input: UserUpdateEmailRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersMeEmailPut(input, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.usersMeEmailPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get current user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersMeGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ModelUser>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersMeGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.usersMeGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Change user password
         * @param {UserUpdatePasswordRequest} input Password change request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersMePasswordPut(input: UserUpdatePasswordRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersMePasswordPut(input, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.usersMePasswordPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Send verification code
         * @param {UserSendVerificationCodeRequest} input Verification request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async usersMeVerificationCodePost(input: UserSendVerificationCodeRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.usersMeVerificationCodePost(input, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.usersMeVerificationCodePost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UserApi - factory interface
 */
export const UserApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UserApiFp(configuration)
    return {
        /**
         * 
         * @summary Upload user avatar
         * @param {File} avatar Avatar file
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersMeAvatarPost(avatar: File, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.usersMeAvatarPost(avatar, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update user email
         * @param {UserUpdateEmailRequest} input Email update request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersMeEmailPut(input: UserUpdateEmailRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.usersMeEmailPut(input, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get current user
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersMeGet(options?: RawAxiosRequestConfig): AxiosPromise<ModelUser> {
            return localVarFp.usersMeGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Change user password
         * @param {UserUpdatePasswordRequest} input Password change request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersMePasswordPut(input: UserUpdatePasswordRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.usersMePasswordPut(input, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Send verification code
         * @param {UserSendVerificationCodeRequest} input Verification request
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        usersMeVerificationCodePost(input: UserSendVerificationCodeRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.usersMeVerificationCodePost(input, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UserApi - object-oriented interface
 */
export class UserApi extends BaseAPI {
    /**
     * 
     * @summary Upload user avatar
     * @param {File} avatar Avatar file
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public usersMeAvatarPost(avatar: File, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).usersMeAvatarPost(avatar, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update user email
     * @param {UserUpdateEmailRequest} input Email update request
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public usersMeEmailPut(input: UserUpdateEmailRequest, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).usersMeEmailPut(input, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get current user
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public usersMeGet(options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).usersMeGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Change user password
     * @param {UserUpdatePasswordRequest} input Password change request
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public usersMePasswordPut(input: UserUpdatePasswordRequest, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).usersMePasswordPut(input, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Send verification code
     * @param {UserSendVerificationCodeRequest} input Verification request
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public usersMeVerificationCodePost(input: UserSendVerificationCodeRequest, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).usersMeVerificationCodePost(input, options).then((request) => request(this.axios, this.basePath));
    }
}



